appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: oiGSf5DZM6vjVcJVuuydiJWE2lGWrVT67249SwPAe1sokHKqmo6/I9eiMFslP4stemstoJDiP4EMgf79D9JBENGM0EmLsFaU/HEPQKWM+QZQsyKAOLfR4sIKUZlMVQuWePBcmAntLUTGAIaGstoWe9tfzAG5hLZO/utEEc9xtTKe4NDWbl3bV3DqlnMPcq11Gl2qSrG948oVeZoWtNiTly3w6QKc/9Dy5Mpfl/BZ/K6MWYJt+dCzcSZiGgseqXSLs6zabPTkz9MMXO7FH+qa643J5yebnzZ3CtHlcpL/EQ23D5VeQfqQNhqh/guWhZLK/HejBPJLedC8PMQ+oN/Evpb7Ox9l0nM5P4dDWggYcCv84kNBssFFIMHpp+6W89G9iMRbt+bFhVTrhHV0s9uFCzyN1woMKlkhqeClwifqcy6clmfD2uqSfkDLuY//i4yb0nBto/dQ4ETdZopkGTxi45Fv6CXgAEJJ0lj52gEdTeQcGKTogpi3YZ4X5K77zl8hqZFC2i0JkI+9OhwvGXQlYqNzxAwZdrOdS34XdEXsUzePnn+noizwyoGospWJzHUU+gkn+MU8Lht++5XTYac9a1SIVqp9NgIef9UP7kxsG06OjyAI+tcnVOwsLmU47VePKN3NxqnOtfhA1c/AyXQEI/7wJ6aMZIjeRf2garbKm0I=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
